-- 0037: let a signed-in staffer see ONLY their own pending GCash QR entries.
--
-- Why this is needed:
-- ────────────────────
-- The QR is generated by the POS the moment the cashier presses GCash. It writes one entry to
-- pos_active_payment_qrs (created in 0036). The cashier's clock-in page on the website needs to
-- see that entry the INSTANT it's written, so the QR can pop up on their phone for the customer
-- to scan. The cleanest way to push that to their phone is the same instant-update plumbing the
-- live PC grid already uses (Supabase Realtime).
--
-- 0036 locked the table down completely — only the trusted server key can read it. That kept
-- the data safe BUT also blocked the cashier's phone from receiving the live entry. This
-- migration opens ONE narrow window: a signed-in staff member can see only entries where
-- THEY are the cashier (matched by their Google sign-in email against the branch_staff list).
-- Nothing else: not other cashiers' entries, not other branches, not received/cancelled history.
--
-- What this DOES NOT do:
-- ──────────────────────
-- - Does NOT let anonymous visitors read the table.
-- - Does NOT let a staffer write or update entries (the POS still owns all writes via the
--   trusted server key).
-- - Does NOT touch existing data — 0036's table + indexes + Realtime publication stay as-is.
--
-- One narrow rule, additive only. Safe to roll back by dropping the policy.

create policy "staff can see their own pending payment qrs"
  on public.pos_active_payment_qrs
  for select
  to authenticated
  using (
    cashier_staff_id in (
      select id
      from public.branch_staff
      where lower(email) = lower(auth.email())
        and status = 'approved'
    )
  );
